### ISSUE TITLE
model.pt file

### ISSUE THREAD

**Issue by anotherotherme** [tryolabs/soccer-video-analytics#2]
Hi. Than you for your work!
Can you please add  ball.pt file for running this code?
I can't run this without the ML model

**Comment by Kr4is** [comment]
any update on this?

**Comment by TalhaaaYaqoob** [comment]
any updates??

**Comment by peps85** [comment]
Up!

**Comment by Donalcon** [comment]
Where is it?

**Comment by christiams** [comment]
where can we found ball.pt?

**Comment by dekked** [comment]
[Released here](https://github.com/tryolabs/soccer-video-analytics/commit/b00c7c75a1d52bd5ca183521a35fc76fbd89cc0e).
