### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Kamo-189** [tryolabs/soccer-video-analytics#7]
Without the ball.pt file, we can not know the weights and architecture of the pre-trained model. And without those information it's pretty hard to run correctly the projet. I guess it would be possible to train the model again with norfair, but that will be perfect if you could just add the ball.pt file on the project !

**Comment by dekked** [comment]
[Released here](https://github.com/tryolabs/soccer-video-analytics/commit/b00c7c75a1d52bd5ca183521a35fc76fbd89cc0e).
